### ISSUE TITLE
Bug report finaltest

### ISSUE THREAD

**Issue by UptitudeIssues** [Studia-Org/studia_frontend#118]
**Nombre:** finaltest
                    **Email:** hola@gmail.com
                    **Mensaje:** test
                    **Screenshot:** ![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247806/ss_gtog_1dc2756c93.png)

**Comment by Topiksit0** [comment]
![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247806/ss_gtog_1dc2756c93.png)
