### ISSUE TITLE
Bug report test123123

### ISSUE THREAD

**Issue by UptitudeIssues** [Studia-Org/studia_frontend#119]
**Nombre:** test123123
                    **Email:** marcospalominovivar@gmail.com
                    **Mensaje:** test
                    ![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247937/ss_gtog_2c9eb85b9e.png)

**Comment by Topiksit0** [comment]
**Nombre:** test123123
                **Email:** marcospalominovivar@gmail.com
                **Mensaje:** test
                ![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247937/ss_gtog_2c9eb85b9e.png)

**Comment by Topiksit0** [comment]
**Nombre:** test123123
            **Email:** marcospalominovivar@gmail.com
            **Mensaje:** test
            
            ![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247937/ss_gtog_2c9eb85b9e.png)

**Comment by Topiksit0** [comment]
**Nombre:** test123123
        **Email:** marcospalominovivar@gmail.com
        **Mensaje:** test  ![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247937/ss_gtog_2c9eb85b9e.png)

**Comment by Topiksit0** [comment]
![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247937/ss_gtog_2c9eb85b9e.png)

**Comment by Topiksit0** [comment]
![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247937/ss_gtog_2c9eb85b9e.png)

**Comment by Topiksit0** [comment]
**Nombre:** test123123
        **Email:** marcospalominovivar@gmail.com
        **Mensaje:** test
![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1712247937/ss_gtog_2c9eb85b9e.png)
