### ISSUE TITLE
Bug report Xu 


### ISSUE THREAD

**Issue by UptitudeIssues** [Studia-Org/studia_frontend#146]
**Nombre:** Xu 
**Email:** xyaochen7@alumnes.ub.edu 
**Mensaje:** We can't scroll down when trying to modify personal data. We can only use the TAB to go through them. 
![image-title](https://res.cloudinary.com/dnmlszkih/image/upload/v1715288082/Captura_de_pantalla_2024_05_09_a_las_22_53_42_ce3b455547.png)

**Comment by rogeranyor** [comment]
Done
